### PR TITLE
ST changes

### PR DESCRIPTION
**Pull request by SpenserTan**
added new column and fixed links for socials

### CODE REVIEW

**Review by sharonsylu — COMMENTED** [review]
@SpenserTan you duplicated the list in the repo. Can repo owner please revert this PR?

**Comment by hboon** [comment]
@sharonsylu If no one has pushed to the repo before me, I can force the repo to point to 388c205 (5th commit in screenshot, which is just before this PR) if you like?

Screenshot 2021-12-05 at 10 16 47 PM

**Comment by sharonsylu** [comment]
its after you @hboon, duplicates in the [`eba320c` ] commit (https://github.com/AlphaWallet/Awesome-Blockchain-Projects-in-Oceania/pull/5/commits/eba320c010d5f9d5533802e12250b742b8e2827f)

**Comment by hboon** [comment]
@sharonsylu can you point me to the commit hash to reset to? eg. eba320c? Note that this PR contributed 4 commits. My contribution was 388c205.

**Comment by sharonsylu** [comment]
Thanks, didn't realise you can revert! Reset back to  https://github.com/AlphaWallet/Awesome-Blockchain-Projects-in-Oceania/pull/5/commits/f78fd3bcf2c7400f132ec6de9b2d44e79f0f96bb please

**Comment by hboon** [comment]
Done. There's a backup at https://github.com/AlphaWallet/Awesome-Blockchain-Projects-in-Oceania/tree/main-backup. Feel free to delete it.

> didn't realise you can revert!

Yes, but we generally don'tt do this often. Gets icky once other collaborators have those commits in their local repo.

**Pull request merged**
